/** Possible lifecycle states of a ticket within the system. */
export type TicketStatus = 'RECEIVED' | 'IN_PROGRESS' | 'RESOLVED';

/** Priority levels a ticket can have (PENDING until Consumer assigns one). */
export type TicketPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'PENDING';

/**
 * Types of ISP incidents that a customer can report.
 *
 * | Incident Type           | Consumer Priority |
 * |-------------------------|-------------------|
 * | `NO_SERVICE`            | HIGH              |
 * | `INTERMITTENT_SERVICE`  | MEDIUM            |
 * | `SLOW_CONNECTION`       | MEDIUM            |
 * | `ROUTER_ISSUE`          | LOW               |
 * | `BILLING_QUESTION`      | LOW               |
 * | `OTHER`                 | PENDING           |
 *
 * @enum {string}
 */
export enum IncidentType {
  /** Total loss of internet service. */
  NO_SERVICE = 'NO_SERVICE',
  /** Connectivity drops intermittently. */
  INTERMITTENT_SERVICE = 'INTERMITTENT_SERVICE',
  /** Connection speed significantly below contracted rate. */
  SLOW_CONNECTION = 'SLOW_CONNECTION',
  /** Customer-premises router/equipment issue. */
  ROUTER_ISSUE = 'ROUTER_ISSUE',
  /** Billing or account inquiry. */
  BILLING_QUESTION = 'BILLING_QUESTION',
  /** Uncategorized incident — requires a `description` field. */
  OTHER = 'OTHER',
}

/**
 * Represents a complaint ticket created by the Producer.
 *
 * Produced by the `complaintsService` after validation and before
 * publishing to RabbitMQ. The Consumer will enrich it with resolved
 * priority and status.
 *
 * @interface Ticket
 */
export interface Ticket {
  /** Unique identifier (UUIDv4) generated by the Producer. */
  ticketId: string;
  /** Customer's ISP line/account number. */
  lineNumber: string;
  /** Customer's email address for notifications. */
  email: string;
  /** Classification of the reported problem. */
  incidentType: IncidentType;
  /** Free-text description. Required when `incidentType === OTHER`; otherwise `null`. */
  description: string | null;
  /** Initial lifecycle status (always `'RECEIVED'` at creation). */
  status: TicketStatus;
  /** Initial priority (always `'PENDING'` until Consumer resolves it). */
  priority: TicketPriority;
  /** Timestamp of ticket creation. */
  createdAt: Date;
}

/**
 * Shape of the HTTP request body for creating a new complaint.
 * Validated by the `validateComplaintRequest` middleware.
 *
 * @interface CreateTicketRequest
 */
export interface CreateTicketRequest {
  /** Customer's ISP line/account number (required). */
  lineNumber: string;
  /** Customer's email address (required, validated format). */
  email: string;
  /** The incident type enum value (required, validated against {@link IncidentType}). */
  incidentType: IncidentType;
  /** Free-text description. **Required only when** `incidentType === 'OTHER'`. */
  description?: string;
}

/**
 * Payload serialized and published to RabbitMQ by the {@link TicketMessageSerializer}.
 * This is the contract between Producer and Consumer.
 *
 * **Important**: Any changes to this interface must be reflected in both
 * the Producer's serializer and the Consumer's `MessageHandler` deserialization.
 *
 * @interface TicketEventPayload
 */
export interface TicketEventPayload {
  /** Unique ticket identifier (UUIDv4). */
  ticketId: string;
  /** Customer's line/account number. */
  lineNumber: string;
  /** Customer's contact email. */
  email: string;
  /** Incident type (maps to {@link IncidentType} on the Consumer side). */
  type: IncidentType;
  /** Free-text description, or `null` if not applicable. */
  description: string | null;
  /** ISO-8601 string representation of the ticket creation timestamp. */
  createdAt: string;
}
