/**
 * Types of ISP incidents that a customer can report.
 *
 * Each value maps to a specific {@link Priority} via the Strategy pattern
 * in the Consumer's `PriorityResolver`.
 *
 * | Incident Type           | Mapped Priority |
 * |-------------------------|-----------------|
 * | `NO_SERVICE`            | HIGH            |
 * | `INTERMITTENT_SERVICE`  | MEDIUM          |
 * | `SLOW_CONNECTION`       | MEDIUM          |
 * | `ROUTER_ISSUE`          | LOW             |
 * | `BILLING_QUESTION`      | LOW             |
 * | `OTHER`                 | PENDING         |
 *
 * @enum {string}
 */
export enum IncidentType {
  /** Total loss of internet service. */
  NO_SERVICE = 'NO_SERVICE',
  /** Connectivity drops intermittently. */
  INTERMITTENT_SERVICE = 'INTERMITTENT_SERVICE',
  /** Connection speed significantly below contracted rate. */
  SLOW_CONNECTION = 'SLOW_CONNECTION',
  /** Customer-premises router/equipment issue. */
  ROUTER_ISSUE = 'ROUTER_ISSUE',
  /** Billing or account inquiry. */
  BILLING_QUESTION = 'BILLING_QUESTION',
  /** Uncategorized incident — requires a `description` field. */
  OTHER = 'OTHER'
}

/**
 * Priority levels assigned to incidents after processing.
 *
 * Resolved by the Consumer's `PriorityResolver` using the Strategy pattern.
 * `PENDING` indicates the incident has not yet been triaged.
 *
 * @enum {string}
 */
export enum Priority {
  /** Critical — requires immediate attention (e.g., NO_SERVICE). */
  HIGH = 'HIGH',
  /** Moderate — degraded service (e.g., INTERMITTENT_SERVICE, SLOW_CONNECTION). */
  MEDIUM = 'MEDIUM',
  /** Low — non-urgent (e.g., ROUTER_ISSUE, BILLING_QUESTION). */
  LOW = 'LOW',
  /** Awaiting manual triage (e.g., OTHER). */
  PENDING = 'PENDING'
}

/**
 * Lifecycle states of an incident within the Consumer.
 *
 * Follows the lifecycle: Recibida → Validada → Encolada → Priorizada → En Progreso.
 * The Consumer currently resolves to either `RECEIVED` (pending triage)
 * or `IN_PROGRESS` (priority assigned and processing started).
 *
 * @enum {string}
 */
export enum IncidentStatus {
  /** Initial state — incident received but not yet fully processed. */
  RECEIVED = 'RECEIVED',
  /** Priority has been assigned and the incident is actively being worked. */
  IN_PROGRESS = 'IN_PROGRESS'
}

/**
 * Represents a fully processed incident persisted in the Consumer's repository.
 *
 * Created by {@link MessageHandler} after deserializing a RabbitMQ message,
 * resolving priority, and determining status.
 *
 * @interface Incident
 */
export interface Incident {
  /** Unique identifier generated by the Producer (UUIDv4). */
  ticketId: string;
  /** Customer's ISP line/account number. */
  lineNumber: string;
  /** Classification of the reported problem. */
  type: IncidentType;
  /** Free-text description. Required when `type === OTHER`; otherwise optional. */
  description?: string;
  /** Priority resolved by the Consumer's `PriorityResolver`. */
  priority: Priority;
  /** Current lifecycle status. */
  status: IncidentStatus;
  /** ISO-8601 timestamp from the Producer indicating when the ticket was created. */
  createdAt: string;
  /** Timestamp set by the Consumer when the message is processed. */
  processedAt?: Date;
}
